export const sampleRecommendations = [
  // ---------- 15 REQUESTED ----------
  {
    itemType: "Book",
    title: "Clean Code",
    author: "Robert C. Martin",
    year: "2008",
    isbn: "9780132350884",
    publisher: "Prentice Hall",
    quantity: "5",
    currency: "INR",
    price: "950",
    category: "Software Engineering",
    vendor: "Pearson India",
    dept: "CSE",
    notes: "Classic reference",
    status: "Requested",
    createdAt: "2024-11-01"
  },
  {
    itemType: "Book",
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum",
    year: "2017",
    isbn: "9789332586936",
    publisher: "Pearson",
    quantity: "4",
    currency: "INR",
    price: "820",
    category: "Networks",
    vendor: "Pearson India",
    dept: "CSE",
    notes: "Required for CN",
    status: "Requested",
    createdAt: "2024-10-25"
  },
  {
    itemType: "Book",
    title: "Modern Control Engineering",
    author: "Katsuhiko Ogata",
    year: "2015",
    isbn: "9789339214320",
    publisher: "Pearson",
    quantity: "3",
    currency: "INR",
    price: "780",
    category: "Control Systems",
    vendor: "Pearson India",
    dept: "EEE",
    notes: "Control theory base",
    status: "Requested",
    createdAt: "2024-10-28"
  },
  {
    itemType: "Book",
    title: "Electric Machinery and Transformers",
    author: "Guru & Hiziroglu",
    year: "2013",
    isbn: "9780199322675",
    publisher: "Oxford",
    quantity: "5",
    currency: "INR",
    price: "900",
    category: "Electrical",
    vendor: "Oxford India",
    dept: "EEE",
    notes: "Core subject",
    status: "Requested",
    createdAt: "2024-09-12"
  },
  {
    itemType: "Book",
    title: "Engineering Drawing",
    author: "N.D. Bhatt",
    year: "2019",
    isbn: "9789385031536",
    publisher: "Charotar",
    quantity: "6",
    currency: "INR",
    price: "600",
    category: "Mechanical",
    vendor: "Charotar Publishers",
    dept: "MECH",
    notes: "First-year requirement",
    status: "Requested",
    createdAt: "2024-09-20"
  },
  {
    itemType: "Book",
    title: "Signals & Linear Systems",
    author: "B.P. Lathi",
    year: "2017",
    isbn: "9780198062282",
    publisher: "Oxford",
    quantity: "5",
    currency: "INR",
    price: "840",
    category: "ECE Core",
    vendor: "Oxford India",
    dept: "ECE",
    notes: "Signals reference",
    status: "Requested",
    createdAt: "2024-11-05"
  },
  {
    itemType: "Book",
    title: "Data Structures Using C",
    author: "Reema Thareja",
    year: "2018",
    isbn: "9780199490800",
    publisher: "Oxford",
    quantity: "7",
    currency: "INR",
    price: "700",
    category: "Programming",
    vendor: "Oxford India",
    dept: "CSE",
    notes: "DSA base book",
    status: "Requested",
    createdAt: "2024-11-12"
  },
  {
    itemType: "Book",
    title: "Digital Signal Processing",
    author: "Proakis & Manolakis",
    year: "2013",
    isbn: "9789332518661",
    publisher: "Pearson",
    quantity: "4",
    currency: "INR",
    price: "950",
    category: "DSP",
    vendor: "Pearson India",
    dept: "ECE",
    notes: "DSP primary reference",
    status: "Requested",
    createdAt: "2024-11-14"
  },
  {
    itemType: "Book",
    title: "Transport Phenomena",
    author: "Bird, Stewart & Lightfoot",
    year: "2015",
    isbn: "9788126556325",
    publisher: "Wiley",
    quantity: "3",
    currency: "INR",
    price: "1200",
    category: "Chemical Engineering",
    vendor: "Wiley India",
    dept: "CHEM",
    notes: "Transport reference",
    status: "Requested",
    createdAt: "2024-10-19"
  },
  {
    itemType: "Book",
    title: "Compiler Design",
    author: "Aho, Sethi, Ullman",
    year: "2006",
    isbn: "9789332544820",
    publisher: "Pearson",
    quantity: "5",
    currency: "INR",
    price: "920",
    category: "Compilers",
    vendor: "Pearson India",
    dept: "CSE",
    notes: "Dragon book",
    status: "Requested",
    createdAt: "2024-11-10"
  },
  {
    itemType: "Book",
    title: "Engineering Chemistry",
    author: "Jain & Jain",
    year: "2017",
    isbn: "9789350141749",
    publisher: "Dhanpat Rai",
    quantity: "6",
    currency: "INR",
    price: "450",
    category: "Chemistry",
    vendor: "Dhanpat Rai",
    dept: "CHEM",
    notes: "First-year reference",
    status: "Requested",
    createdAt: "2024-10-08"
  },
  {
    itemType: "Book",
    title: "Basic Electronics",
    author: "Sedra & Smith",
    year: "2020",
    isbn: "9780190856131",
    publisher: "Oxford",
    quantity: "4",
    currency: "INR",
    price: "980",
    category: "Electronics",
    vendor: "Oxford India",
    dept: "ECE",
    notes: "Electronics base book",
    status: "Requested",
    createdAt: "2024-11-03"
  },
  {
    itemType: "Book",
    title: "Industrial Instrumentation",
    author: "Doebelin",
    year: "2011",
    isbn: "9780073375432",
    publisher: "McGraw Hill",
    quantity: "3",
    currency: "INR",
    price: "960",
    category: "Instrumentation",
    vendor: "McGraw Hill India",
    dept: "EEE",
    notes: "Measuring instruments",
    status: "Requested",
    createdAt: "2024-09-29"
  },
  {
    itemType: "Book",
    title: "Strength of Materials",
    author: "S.S. Rattan",
    year: "2014",
    isbn: "9780073638957",
    publisher: "McGraw Hill",
    quantity: "7",
    currency: "INR",
    price: "720",
    category: "Mechanical",
    vendor: "McGraw Hill India",
    dept: "MECH",
    notes: "Core mechanics",
    status: "Requested",
    createdAt: "2024-10-02"
  },
  {
    itemType: "Book",
    title: "Theory of Machines",
    author: "R.S. Khurmi",
    year: "2012",
    isbn: "9788177000285",
    publisher: "S. Chand",
    quantity: "6",
    currency: "INR",
    price: "580",
    category: "Mechanical",
    vendor: "S. Chand",
    dept: "MECH",
    notes: "Machine theory",
    status: "Requested",
    createdAt: "2024-11-15"
  },

  // ---------- 15 APPROVED ----------
  {
    itemType: "Book",
    title: "Digital Design",
    author: "Morris Mano",
    year: "2017",
    isbn: "9789332549702",
    publisher: "Pearson",
    quantity: "6",
    currency: "INR",
    price: "670",
    category: "Electronics",
    vendor: "Pearson India",
    dept: "EEE",
    notes: "Digital logic basics",
    status: "Approved",
    createdAt: "2024-08-21"
  },
  {
    itemType: "Book",
    title: "AI: A Modern Approach",
    author: "Russell & Norvig",
    year: "2021",
    isbn: "9780134610993",
    publisher: "Pearson",
    quantity: "4",
    currency: "INR",
    price: "1200",
    category: "AI",
    vendor: "Pearson India",
    dept: "CSE",
    notes: "AI core book",
    status: "Approved",
    createdAt: "2024-08-10"
  },
  {
    itemType: "Book",
    title: "Advanced Engineering Mathematics",
    author: "Kreyszig",
    year: "2015",
    isbn: "9788126554232",
    publisher: "Wiley",
    quantity: "7",
    currency: "INR",
    price: "780",
    category: "Math",
    vendor: "Wiley India",
    dept: "MATH",
    notes: "UG reference",
    status: "Approved",
    createdAt: "2024-07-14"
  },
  {
    itemType: "Book",
    title: "Signals & Systems",
    author: "Oppenheim",
    year: "2015",
    isbn: "9789332543113",
    publisher: "Pearson",
    quantity: "3",
    currency: "INR",
    price: "760",
    category: "ECE",
    vendor: "Pearson India",
    dept: "ECE",
    notes: "Core ECE",
    status: "Approved",
    createdAt: "2024-07-09"
  },
  {
    itemType: "Book",
    title: "Fluid Mechanics",
    author: "Frank White",
    year: "2016",
    isbn: "9780071333120",
    publisher: "McGraw Hill",
    quantity: "4",
    currency: "INR",
    price: "890",
    category: "Fluid Dynamics",
    vendor: "UBS Publishers",
    dept: "CHEM",
    notes: "Preferred book",
    status: "Approved",
    createdAt: "2024-06-22"
  },
  {
    itemType: "Book",
    title: "Thermodynamics",
    author: "Cengel",
    year: "2017",
    isbn: "9789339222080",
    publisher: "McGraw Hill",
    quantity: "5",
    currency: "INR",
    price: "900",
    category: "Mechanical",
    vendor: "UBS",
    dept: "MECH",
    notes: "Thermo core",
    status: "Approved",
    createdAt: "2024-06-30"
  },
  {
    itemType: "Book",
    title: "Control Systems Engineering",
    author: "Norman Nise",
    year: "2019",
    isbn: "9788126578856",
    publisher: "Wiley",
    quantity: "4",
    currency: "INR",
    price: "840",
    category: "Control",
    vendor: "Wiley India",
    dept: "ECE",
    notes: "UG control",
    status: "Approved",
    createdAt: "2024-07-02"
  },
  {
    itemType: "Book",
    title: "Data Communication & Networking",
    author: "Forouzan",
    year: "2017",
    isbn: "9789330542552",
    publisher: "McGraw Hill",
    quantity: "6",
    currency: "INR",
    price: "750",
    category: "Networks",
    vendor: "McGraw Hill India",
    dept: "CSE",
    notes: "CN reference",
    status: "Approved",
    createdAt: "2024-06-05"
  },
  {
    itemType: "Book",
    title: "Discrete Mathematics",
    author: "Rosen",
    year: "2019",
    isbn: "9789332519125",
    publisher: "McGraw Hill",
    quantity: "6",
    currency: "INR",
    price: "820",
    category: "Math",
    vendor: "McGraw Hill India",
    dept: "CSE",
    notes: "DSA pre-requisite",
    status: "Approved",
    createdAt: "2024-06-15"
  },
  {
    itemType: "Book",
    title: "Communication Systems",
    author: "Haykin",
    year: "2014",
    isbn: "9788126511099",
    publisher: "Wiley",
    quantity: "4",
    currency: "INR",
    price: "860",
    category: "Communications",
    vendor: "Wiley India",
    dept: "ECE",
    notes: "ECE reference",
    status: "Approved",
    createdAt: "2024-07-18"
  },
  {
    itemType: "Book",
    title: "Probability & Statistics",
    author: "Jay Devore",
    year: "2016",
    isbn: "9788131532466",
    publisher: "Cengage",
    quantity: "5",
    currency: "INR",
    price: "690",
    category: "Statistics",
    vendor: "Cengage India",
    dept: "MATH",
    notes: "Statistics lab",
    status: "Approved",
    createdAt: "2024-06-12"
  },
  {
    itemType: "Book",
    title: "Heat Transfer",
    author: "Holman",
    year: "2018",
    isbn: "9789339205434",
    publisher: "McGraw Hill",
    quantity: "6",
    currency: "INR",
    price: "780",
    category: "MECH",
    vendor: "McGraw Hill India",
    dept: "MECH",
    notes: "ME heat transfer",
    status: "Approved",
    createdAt: "2024-05-22"
  },
  {
    itemType: "Book",
    title: "Numerical Methods",
    author: "Chapra",
    year: "2019",
    isbn: "9780073397922",
    publisher: "McGraw Hill",
    quantity: "5",
    currency: "INR",
    price: "830",
    category: "Math",
    vendor: "UBS",
    dept: "MECH",
    notes: "Computational labs",
    status: "Approved",
    createdAt: "2024-05-15"
  },
  {
    itemType: "Book",
    title: "Power System Analysis",
    author: "Grainger",
    year: "2015",
    isbn: "9788120344136",
    publisher: "McGraw Hill",
    quantity: "3",
    currency: "INR",
    price: "960",
    category: "Electrical",
    vendor: "UBS",
    dept: "EEE",
    notes: "EEE analysis",
    status: "Approved",
    createdAt: "2024-08-01"
  },
  {
    itemType: "Book",
    title: "Machine Learning",
    author: "Kevin Murphy",
    year: "2021",
    isbn: "9780262047956",
    publisher: "MIT Press",
    quantity: "4",
    currency: "INR",
    price: "1250",
    category: "AI/ML",
    vendor: "MIT Distributor",
    dept: "CSE",
    notes: "Advanced ML",
    status: "Approved",
    createdAt: "2024-08-08"
  },

  // ---------- 15 REJECTED ----------
  {
    itemType: "Book",
    title: "Quantum Physics",
    author: "H.C. Verma",
    year: "2012",
    isbn: "9788121924979",
    publisher: "Bharti Bhawan",
    quantity: "4",
    currency: "INR",
    price: "550",
    category: "Physics",
    vendor: "Bharti Bhawan",
    dept: "PHY",
    notes: "Duplicate copies exist",
    status: "Rejected",
    createdAt: "2024-09-14"
  },
  {
    itemType: "Book",
    title: "MATLAB for Engineers",
    author: "Holly Moore",
    year: "2017",
    isbn: "9789339221687",
    publisher: "Pearson",
    quantity: "3",
    currency: "INR",
    price: "700",
    category: "Software",
    vendor: "Pearson India",
    dept: "EEE",
    notes: "Not required in new syllabus",
    status: "Rejected",
    createdAt: "2024-09-03"
  },
  {
    itemType: "Book",
    title: "Environmental Engineering",
    author: "Peavy & Rowe",
    year: "2014",
    isbn: "9788120305648",
    publisher: "McGraw Hill",
    quantity: "5",
    currency: "INR",
    price: "650",
    category: "Environment",
    vendor: "McGraw Hill India",
    dept: "CIVIL",
    notes: "Low utilization",
    status: "Rejected",
    createdAt: "2024-08-29"
  },
  {
    itemType: "Book",
    title: "Microwave Engineering",
    author: "Pozar",
    year: "2013",
    isbn: "9788120328074",
    publisher: "Wiley",
    quantity: "3",
    currency: "INR",
    price: "980",
    category: "ECE",
    vendor: "Wiley India",
    dept: "ECE",
    notes: "Already available",
    status: "Rejected",
    createdAt: "2024-09-12"
  },
  {
    itemType: "Book",
    title: "Engineering Physics",
    author: "Gaur & Gupta",
    year: "2016",
    isbn: "9788174090739",
    publisher: "Dhanpat Rai",
    quantity: "6",
    currency: "INR",
    price: "450",
    category: "Physics",
    vendor: "Dhanpat Rai",
    dept: "PHY",
    notes: "Duplicate title",
    status: "Rejected",
    createdAt: "2024-09-18"
  },
  {
    itemType: "Book",
    title: "Structural Analysis",
    author: "R.C. Hibbeler",
    year: "2017",
    isbn: "9780134444017",
    publisher: "Pearson",
    quantity: "4",
    currency: "INR",
    price: "900",
    category: "Civil",
    vendor: "Pearson India",
    dept: "CIVIL",
    notes: "Not prioritized",
    status: "Rejected",
    createdAt: "2024-09-07"
  },
  {
    itemType: "Book",
    title: "Hydraulics & Fluid Mechanics",
    author: "Modi & Seth",
    year: "2010",
    isbn: "9788187436951",
    publisher: "Standard Book House",
    quantity: "5",
    currency: "INR",
    price: "500",
    category: "Civil",
    vendor: "SBH",
    dept: "CIVIL",
    notes: "Old edition",
    status: "Rejected",
    createdAt: "2024-09-10"
  },
  {
    itemType: "Book",
    title: "Robotics Engineering",
    author: "Craig",
    year: "2017",
    isbn: "9789339256221",
    publisher: "Pearson",
    quantity: "3",
    currency: "INR",
    price: "1200",
    category: "Robotics",
    vendor: "Pearson India",
    dept: "MECH",
    notes: "Budget constraints",
    status: "Rejected",
    createdAt: "2024-08-30"
  },
  {
    itemType: "Book",
    title: "Polymer Science",
    author: "Billmeyer",
    year: "2013",
    isbn: "9788120338936",
    publisher: "McGraw Hill",
    quantity: "4",
    currency: "INR",
    price: "780",
    category: "Chemistry",
    vendor: "McGraw Hill",
    dept: "CHEM",
    notes: "Low demand",
    status: "Rejected",
    createdAt: "2024-09-05"
  },
  {
    itemType: "Book",
    title: "Automotive Engineering",
    author: "Kirpal Singh",
    year: "2012",
    isbn: "9788185015165",
    publisher: "Standard",
    quantity: "7",
    currency: "INR",
    price: "650",
    category: "Automobile",
    vendor: "Standard Publishers",
    dept: "MECH",
    notes: "Not in syllabus",
    status: "Rejected",
    createdAt: "2024-09-15"
  },
  {
    itemType: "Book",
    title: "Biochemical Engineering",
    author: "Bailey & Ollis",
    year: "2013",
    isbn: "9788126553074",
    publisher: "McGraw Hill",
    quantity: "3",
    currency: "INR",
    price: "880",
    category: "Biochemical",
    vendor: "McGraw Hill",
    dept: "CHEM",
    notes: "Rare usage",
    status: "Rejected",
    createdAt: "2024-08-19"
  },
  {
    itemType: "Book",
    title: "Human Anatomy",
    author: "Marieb",
    year: "2015",
    isbn: "9789332549804",
    publisher: "Pearson",
    quantity: "4",
    currency: "INR",
    price: "950",
    category: "Biology",
    vendor: "Pearson India",
    dept: "BIO",
    notes: "Not required",
    status: "Rejected",
    createdAt: "2024-08-23"
  },
  {
    itemType: "Book",
    title: "Manufacturing Processes",
    author: "Kalpakjian",
    year: "2014",
    isbn: "9789339205239",
    publisher: "Pearson",
    quantity: "3",
    currency: "INR",
    price: "1100",
    category: "Manufacturing",
    vendor: "Pearson India",
    dept: "MECH",
    notes: "Very old edition",
    status: "Rejected",
    createdAt: "2024-08-26"
  },
  {
    itemType: "Book",
    title: "Database Systems",
    author: "Raghu Ramakrishnan",
    year: "2012",
    isbn: "9780071289595",
    publisher: "McGraw Hill",
    quantity: "4",
    currency: "INR",
    price: "850",
    category: "DBMS",
    vendor: "McGraw Hill India",
    dept: "CSE",
    notes: "Sufficient copies exist",
    status: "Rejected",
    createdAt: "2024-09-01"
  },
  {
    itemType: "Book",
    title: "Circuit Analysis",
    author: "Charles Alexander",
    year: "2016",
    isbn: "9781259860953",
    publisher: "McGraw Hill",
    quantity: "4",
    currency: "INR",
    price: "780",
    category: "Electrical",
    vendor: "McGraw Hill India",
    dept: "EEE",
    notes: "Older version",
    status: "Rejected",
    createdAt: "2024-09-20"
  }
];
